# Generated by Django 6.1 on 2026-08-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
