# Generated by Django 6.1 on 2026-08-06 13:00

from django.db import migrations


def populate_fullnames(apps, schema_editor):
    Student = apps.get_model(
        "students",
        "Student"
    )

    students = Student.objects.all()
    for student in students:
        student.full_name = (
            f"{student.firstname} {student.surname}"
        )
        student.save()



class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_student_registration_number_student_full_name'),
    ]

    operations = [
        migrations.RunPython(populate_fullnames)
    ]
